[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
[[headers]]
  for = "/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/font/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/static/gen/fonts/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"   
[[headers]]
  for = "/static/gen/css/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/static/gen/js/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/css/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "/manifest.json"
    [headers.values]
    Cache-Control = "public, max-age=600"
[[headers]]
  for = "/js/cuadrantes.json"
    [headers.values]
    Cache-Control = "public, max-age=600"
[[headers]]
  for = "/js/sectores.json"
    [headers.values]
    Cache-Control = "public, max-age=600"
[[headers]]
  for = "/js/cuadrantes-interactive.json"
    [headers.values]
    Cache-Control = "public, max-age=600"
[[headers]]
  for = "/js/sectores-interactive.json"
    [headers.values]
    Cache-Control = "public, max-age=600"

